name: PHPCBF Auto-Fix

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpcbf-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          persist-credentials: false

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install PHPCS
        run: |
          composer global require squizlabs/php_codesniffer
          echo "$HOME/.config/composer/vendor/bin" >> $GITHUB_PATH

      - name: Run PHPCBF
        run: |
          phpcbf --standard=PSR12 phpcbf/ || true
          if ! git diff --quiet; then
            echo "PHPCBF_CHANGED=true" >> $GITHUB_ENV
          else
            echo "PHPCBF_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Commit & Push fixes
        if: env.PHPCBF_CHANGED == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "PHPCBF: auto-fix coding standards"
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          git fetch origin $BRANCH
          git rebase origin/$BRANCH
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:$BRANCH